
DROP TABLE used CASCADE CONSTRAINTS;
DROP TABLE worked CASCADE CONSTRAINTS;
DROP TABLE maintenance_report CASCADE CONSTRAINTS;
DROP TABLE maintenance_request CASCADE CONSTRAINTS;
DROP TABLE equipment CASCADE CONSTRAINTS;
DROP TABLE team CASCADE CONSTRAINTS;
DROP TABLE departmant CASCADE CONSTRAINTS;
DROP TABLE member_of CASCADE CONSTRAINTS;
DROP TABLE employee CASCADE CONSTRAINTS;
